### ISSUE TITLE
Sharik v3.0 checklist

### ISSUE THREAD

**Issue by marchellodev** [marchellodev/sharik#63]
Hello everyone!

I think Sharik v3 is almost ready. This is the biggest update so far, featuring dark theme, landscape mode support, the about screen, and more! For full changelog, please refer to [CHANGELOG.md](https://github.com/marchellodev/sharik/blob/master/CHANGELOG.md) (note that it is not the final version and this file does not yet contain all changes)

However, there are three more things that need to be done: translation, style tweaks, and bug fixes.

Speaking of translations, they were migrated to a new format (Dart code -> Arb), and there were some text changes. For now, only English version work properly, so I hope to migrate the rest of the languages by the end of the week. Also, we are moving to the [crowdin](https://crowdin.com/project/sharik) to manage the translation files. It is a very useful application to help us manage all the translations. I would appreciate if you guys could help me transfer all translations from dart code to this platform, since there are some major text changes.

Here's the checklist (that I will be updating) of migrated languages:
- [x] English
- [x] Russian (by @marchellodev)
- [x] Ukrainain (by @marchellodev)
- [x] Simplified Chinese (by @zerofancy)
- [x] Arabic (by @YazeedAlKhalaf)
- [ ] Gujarati (by @mrfoxie)
- [ ] Hindi (by @mrfoxie)
- [x] Italian (by @DavideBottasso)
- [x] Malayalam (by @zcraber)
- [x] Persian (by @behzad-njf)
- [x] Polish (by @Atrate)
- [x] Portuguese, Brazilian (by @mezysinc)
- [ ] Sinhala (by @Aikatsui)
- [x] Slovak (by @tiborepcek)
- [x] Turkish (by @tekrei)
- [x] Indonesian (by @liimee)

I would very much appreciate, if you could submit all those translations to the Crowdin (https://crowdin.com/project/sharik). After you are done, please leave a message below.

As those are the final steps, I still would like to do some UI tweaks (mainly fonts and colors), and conduct testing.

I am also going to do some tesing, here's the estimated release checklist for me (that I'll keep updated):
- [x] iOS app
- [x] MacOS app
- [x] Android app
- [x] Windows app
- [x] Linux app
- [x] Review all todos in the code
- [x] Review file names encoding (#59)
- [x] Review RTL mode
- [x] Styling (review all fonts)
- [x] Styling (paddings)
- [x] Styling (colors)
- [x] Migrate `store.yaml` to crowdin
- [x] Check Receiver timeout for extra large files
- [x] iOS file naming
- [x] Check Sharing dot files
- [x] Linux flatpak packaging
- [x] Linux deb packaging
- [x] Linux rpm packaging
- [x] Linux snap packaging
- [x] Windows msi packaging

I have attached the current versions of the app below. Please feel free to try them out and leave feedback or any suggestions.
Also, keep in mind that for now only English translation works and some links (privacy policy, etc) do not work yet.

Thank you all for all the help!

[android.zip](https://github.com/marchellodev/sharik/files/6663766/android.zip)
[linux.zip](https://github.com/marchellodev/sharik/files/6663767/linux.zip)
[windows.zip](https://github.com/marchellodev/sharik/files/6663770/windows.zip)

**Comment by tekrei** [comment]
Turkish translation is done.

**Comment by tiborepcek** [comment]
Slovak translation is done.

**Comment by zcraber** [comment]
Malayalam translation is done.

**Comment by zerofancy** [comment]
Simplified Chinese is done.

**Comment by YazeedAlKhalaf** [comment]
Arabic is done! 🚀

**Comment by zcraber** [comment]
I've tested v3 on Android. Works great!
It'll be nice if there is a **built-in QR code scanner** (related to #22). 
Also, eagerly waiting for the implementation of #24 as well.

**Comment by marchellodev** [comment]
@zcraber Thanks for the test and suggestions!

I do not think that it is reasonable to add QR code scanner to the app, since if you have Sharik on both devices already - you can just use Receiver. On top of that, I found only [one library](https://pub.dev/packages/qr_code_scanner) to do that, which will only work on Android and iOS. Also, then the minimum version of Android will have to be Android 5 (currently we support 4.1+).

Speaking of #24, that's a fantastic idea that will be definitely implemented later, just not in this release.

Thanks again!

**Comment by liimee** [comment]
Indonesian translation is done :)

**Comment by liimee** [comment]
Indonesian translation is done :)

**Comment by marchellodev** [comment]
@behzad-njf @YazeedAlKhalaf As far as I understand, Arabic and Farsi are written right-to-left (as opposed to left-to-right as in English and other languages). Can you please check if Sharik looks natural in this mode? Ignore that languages are not yet embedded, just check the structure of the app.

 I am worrying about that a bit

Thanks a lot!

**Comment by YazeedAlKhalaf** [comment]
> @behzad-njf @YazeedAlKhalaf As far as I understand, Arabic and Farsi are written right-to-left (as opposed to left-to-right as in English and other languages). Can you please check if Sharik looks natural in this mode? Ignore that languages are not yet embedded, just check the structure of the app.
> 
> I am worrying about that a bit
> 
> Thanks a lot!

Nope we should add a check for rtl languages and make the app rtl, with directionality widget i beleive

**Comment by marchellodev** [comment]
@YazeedAlKhalaf In 3.0 we've migrated to Flutter's official implementation of localizations, so now it does that automatically. This is the screenshot on the Linux build (attached to this post) with selected Arabic locale. I just think it looks a bit weird, but I have no idea how it should look, since I haven't dealt with RTL before.

![image](https://user-images.githubusercontent.com/61112084/122678312-ee938900-d1ee-11eb-876c-483a8025fd86.png)

**Comment by YazeedAlKhalaf** [comment]
> @YazeedAlKhalaf In 3.0 we've migrated to Flutter's official implementation of localizations, so now it does that automatically. This is the screenshot on the Linux build (attached to this post) with selected Arabic locale. I just think it looks a bit weird, but I have no idea how it should look, since I haven't dealt with RTL before.
> 
> ![image](https://user-images.githubusercontent.com/61112084/122678312-ee938900-d1ee-11eb-876c-483a8025fd86.png)

There are some trivial details that need checking like the arrow should be flipped and stuff like this. I suggest creating a static method in the utils that returns a bool checking if the language is rtl or not. We would use a switch case statement and add all rtl cases in the case and return false in default.

**Comment by YazeedAlKhalaf** [comment]
> @YazeedAlKhalaf In 3.0 we've migrated to Flutter's official implementation of localizations, so now it does that automatically. This is the screenshot on the Linux build (attached to this post) with selected Arabic locale. I just think it looks a bit weird, but I have no idea how it should look, since I haven't dealt with RTL before.
> 
> ![image](https://user-images.githubusercontent.com/61112084/122678312-ee938900-d1ee-11eb-876c-483a8025fd86.png)

There are some trivial details that need checking like the arrow should be flipped and stuff like this. I suggest creating a static method in the utils that returns a bool checking if the language is rtl or not. We

**Comment by DavideBottasso** [comment]
Italian translation done.

**Comment by mezysinc** [comment]
#64

**Comment by mezysinc** [comment]
Translation for ptbr are in PR #64

**Comment by marchellodev** [comment]
Hey everyone, doing some final tweaks to make sure that 'Share via' feature works properly on iOS.

Just a kind reminder to @mrfoxie @Aikatsui (also, @behzad-njf and @DavideBottasso - your translations are incomplete) to submit your translations to crowdin if you have some time and desire ❤️

Thank you!

**Comment by DavideBottasso** [comment]
> Hey everyone, doing some final tweaks to make sure that 'Share via' feature works properly on iOS.
> 
> Just a kind reminder to @mrfoxie @Aikatsui (also, @behzad-njf and @DavideBottasso - your translations are incomplete) to submit your translations to crowdin if you have some time and desire ❤️
> 
> Thank you!

Hi, translation done at 100%, I didn't see your reply on crowdin.

**Comment by marchellodev** [comment]
Hey everyone, I am almost done researching and implemeting different types of packaging (mostly for linux). I hope to start rolling out v3 tomorrow. Thank you all for the hard work! I'll keep you updated

**Comment by marchellodev** [comment]
Thank y'all, v3 is out!

**Comment by Neyl-123** [comment]
There is a checkmark at "Linux flatpak packaging" but I can't find it on Flathub. Is there a custom remote or am I missing something else?

**Comment by CodeCubeNeo** [comment]
Any updates on the flatpak distribution of this app?
